/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationAuditRouteImport } from './routes/validation-audit'
import { Route as TranscriptsRouteImport } from './routes/transcripts'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResultEntryRouteImport } from './routes/result-entry'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentRegisterRouteImport } from './routes/student.register'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentCarryoversRouteImport } from './routes/student.carryovers'
import { Route as LecturerLoginRouteImport } from './routes/lecturer.login'
import { Route as LecturerEntryRouteImport } from './routes/lecturer.entry'
import { Route as LecturerDashboardRouteImport } from './routes/lecturer.dashboard'
import { Route as FacultyTranscriptsRouteImport } from './routes/faculty.transcripts'
import { Route as FacultyStudentsRouteImport } from './routes/faculty.students'
import { Route as FacultyResultsRouteImport } from './routes/faculty.results'
import { Route as FacultyResultEntryRouteImport } from './routes/faculty.result-entry'
import { Route as FacultyRegistrationLinksRouteImport } from './routes/faculty.registration-links'
import { Route as FacultyLoginRouteImport } from './routes/faculty.login'
import { Route as FacultyDeptAdminsRouteImport } from './routes/faculty.dept-admins'
import { Route as FacultyDashboardRouteImport } from './routes/faculty.dashboard'
import { Route as FacultyCoursesRouteImport } from './routes/faculty.courses'
import { Route as FacultyCarryoversRouteImport } from './routes/faculty.carryovers'
import { Route as DeptAdminLoginRouteImport } from './routes/dept-admin.login'
import { Route as DeptAdminLecturersRouteImport } from './routes/dept-admin.lecturers'
import { Route as DeptAdminDashboardRouteImport } from './routes/dept-admin.dashboard'
import { Route as DeptAdminAssignmentsRouteImport } from './routes/dept-admin.assignments'
import { Route as DeptAdminApprovalsRouteImport } from './routes/dept-admin.approvals'
import { Route as AdminRegistrationLinksRouteImport } from './routes/admin.registration-links'
import { Route as AdminFacultyAdminsRouteImport } from './routes/admin.faculty-admins'
import { Route as AdminFacultiesRouteImport } from './routes/admin.faculties'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const ValidationAuditRoute = ValidationAuditRouteImport.update({
  id: '/validation-audit',
  path: '/validation-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultEntryRoute = ResultEntryRouteImport.update({
  id: '/result-entry',
  path: '/result-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRegisterRoute = StudentRegisterRouteImport.update({
  id: '/student/register',
  path: '/student/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCarryoversRoute = StudentCarryoversRouteImport.update({
  id: '/student/carryovers',
  path: '/student/carryovers',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerLoginRoute = LecturerLoginRouteImport.update({
  id: '/lecturer/login',
  path: '/lecturer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerEntryRoute = LecturerEntryRouteImport.update({
  id: '/lecturer/entry',
  path: '/lecturer/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerDashboardRoute = LecturerDashboardRouteImport.update({
  id: '/lecturer/dashboard',
  path: '/lecturer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyTranscriptsRoute = FacultyTranscriptsRouteImport.update({
  id: '/faculty/transcripts',
  path: '/faculty/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyStudentsRoute = FacultyStudentsRouteImport.update({
  id: '/faculty/students',
  path: '/faculty/students',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyResultsRoute = FacultyResultsRouteImport.update({
  id: '/faculty/results',
  path: '/faculty/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyResultEntryRoute = FacultyResultEntryRouteImport.update({
  id: '/faculty/result-entry',
  path: '/faculty/result-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRegistrationLinksRoute =
  FacultyRegistrationLinksRouteImport.update({
    id: '/faculty/registration-links',
    path: '/faculty/registration-links',
    getParentRoute: () => rootRouteImport,
  } as any)
const FacultyLoginRoute = FacultyLoginRouteImport.update({
  id: '/faculty/login',
  path: '/faculty/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDeptAdminsRoute = FacultyDeptAdminsRouteImport.update({
  id: '/faculty/dept-admins',
  path: '/faculty/dept-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty/dashboard',
  path: '/faculty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyCoursesRoute = FacultyCoursesRouteImport.update({
  id: '/faculty/courses',
  path: '/faculty/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyCarryoversRoute = FacultyCarryoversRouteImport.update({
  id: '/faculty/carryovers',
  path: '/faculty/carryovers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminLoginRoute = DeptAdminLoginRouteImport.update({
  id: '/dept-admin/login',
  path: '/dept-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminLecturersRoute = DeptAdminLecturersRouteImport.update({
  id: '/dept-admin/lecturers',
  path: '/dept-admin/lecturers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminDashboardRoute = DeptAdminDashboardRouteImport.update({
  id: '/dept-admin/dashboard',
  path: '/dept-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminAssignmentsRoute = DeptAdminAssignmentsRouteImport.update({
  id: '/dept-admin/assignments',
  path: '/dept-admin/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminApprovalsRoute = DeptAdminApprovalsRouteImport.update({
  id: '/dept-admin/approvals',
  path: '/dept-admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationLinksRoute = AdminRegistrationLinksRouteImport.update({
  id: '/admin/registration-links',
  path: '/admin/registration-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultyAdminsRoute = AdminFacultyAdminsRouteImport.update({
  id: '/admin/faculty-admins',
  path: '/admin/faculty-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/admin/faculties',
  path: '/admin/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit-logs': typeof AuditLogsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/programmes': typeof ProgrammesRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/faculty-admins': typeof AdminFacultyAdminsRoute
  '/admin/registration-links': typeof AdminRegistrationLinksRoute
  '/dept-admin/approvals': typeof DeptAdminApprovalsRoute
  '/dept-admin/assignments': typeof DeptAdminAssignmentsRoute
  '/dept-admin/dashboard': typeof DeptAdminDashboardRoute
  '/dept-admin/lecturers': typeof DeptAdminLecturersRoute
  '/dept-admin/login': typeof DeptAdminLoginRoute
  '/faculty/carryovers': typeof FacultyCarryoversRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/dept-admins': typeof FacultyDeptAdminsRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/registration-links': typeof FacultyRegistrationLinksRoute
  '/faculty/result-entry': typeof FacultyResultEntryRoute
  '/faculty/results': typeof FacultyResultsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/faculty/transcripts': typeof FacultyTranscriptsRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/entry': typeof LecturerEntryRoute
  '/lecturer/login': typeof LecturerLoginRoute
  '/student/carryovers': typeof StudentCarryoversRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/results': typeof StudentResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit-logs': typeof AuditLogsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/programmes': typeof ProgrammesRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/faculty-admins': typeof AdminFacultyAdminsRoute
  '/admin/registration-links': typeof AdminRegistrationLinksRoute
  '/dept-admin/approvals': typeof DeptAdminApprovalsRoute
  '/dept-admin/assignments': typeof DeptAdminAssignmentsRoute
  '/dept-admin/dashboard': typeof DeptAdminDashboardRoute
  '/dept-admin/lecturers': typeof DeptAdminLecturersRoute
  '/dept-admin/login': typeof DeptAdminLoginRoute
  '/faculty/carryovers': typeof FacultyCarryoversRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/dept-admins': typeof FacultyDeptAdminsRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/registration-links': typeof FacultyRegistrationLinksRoute
  '/faculty/result-entry': typeof FacultyResultEntryRoute
  '/faculty/results': typeof FacultyResultsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/faculty/transcripts': typeof FacultyTranscriptsRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/entry': typeof LecturerEntryRoute
  '/lecturer/login': typeof LecturerLoginRoute
  '/student/carryovers': typeof StudentCarryoversRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/results': typeof StudentResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit-logs': typeof AuditLogsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/programmes': typeof ProgrammesRoute
  '/result-entry': typeof ResultEntryRoute
  '/results': typeof ResultsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/transcripts': typeof TranscriptsRoute
  '/validation-audit': typeof ValidationAuditRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/faculty-admins': typeof AdminFacultyAdminsRoute
  '/admin/registration-links': typeof AdminRegistrationLinksRoute
  '/dept-admin/approvals': typeof DeptAdminApprovalsRoute
  '/dept-admin/assignments': typeof DeptAdminAssignmentsRoute
  '/dept-admin/dashboard': typeof DeptAdminDashboardRoute
  '/dept-admin/lecturers': typeof DeptAdminLecturersRoute
  '/dept-admin/login': typeof DeptAdminLoginRoute
  '/faculty/carryovers': typeof FacultyCarryoversRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/dept-admins': typeof FacultyDeptAdminsRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/registration-links': typeof FacultyRegistrationLinksRoute
  '/faculty/result-entry': typeof FacultyResultEntryRoute
  '/faculty/results': typeof FacultyResultsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/faculty/transcripts': typeof FacultyTranscriptsRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/entry': typeof LecturerEntryRoute
  '/lecturer/login': typeof LecturerLoginRoute
  '/student/carryovers': typeof StudentCarryoversRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/results': typeof StudentResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/programmes'
    | '/result-entry'
    | '/results'
    | '/schools'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
    | '/admin/analytics'
    | '/admin/faculties'
    | '/admin/faculty-admins'
    | '/admin/registration-links'
    | '/dept-admin/approvals'
    | '/dept-admin/assignments'
    | '/dept-admin/dashboard'
    | '/dept-admin/lecturers'
    | '/dept-admin/login'
    | '/faculty/carryovers'
    | '/faculty/courses'
    | '/faculty/dashboard'
    | '/faculty/dept-admins'
    | '/faculty/login'
    | '/faculty/registration-links'
    | '/faculty/result-entry'
    | '/faculty/results'
    | '/faculty/students'
    | '/faculty/transcripts'
    | '/lecturer/dashboard'
    | '/lecturer/entry'
    | '/lecturer/login'
    | '/student/carryovers'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/login'
    | '/student/profile'
    | '/student/register'
    | '/student/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/programmes'
    | '/result-entry'
    | '/results'
    | '/schools'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
    | '/admin/analytics'
    | '/admin/faculties'
    | '/admin/faculty-admins'
    | '/admin/registration-links'
    | '/dept-admin/approvals'
    | '/dept-admin/assignments'
    | '/dept-admin/dashboard'
    | '/dept-admin/lecturers'
    | '/dept-admin/login'
    | '/faculty/carryovers'
    | '/faculty/courses'
    | '/faculty/dashboard'
    | '/faculty/dept-admins'
    | '/faculty/login'
    | '/faculty/registration-links'
    | '/faculty/result-entry'
    | '/faculty/results'
    | '/faculty/students'
    | '/faculty/transcripts'
    | '/lecturer/dashboard'
    | '/lecturer/entry'
    | '/lecturer/login'
    | '/student/carryovers'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/login'
    | '/student/profile'
    | '/student/register'
    | '/student/results'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/login'
    | '/programmes'
    | '/result-entry'
    | '/results'
    | '/schools'
    | '/sessions'
    | '/students'
    | '/transcripts'
    | '/validation-audit'
    | '/admin/analytics'
    | '/admin/faculties'
    | '/admin/faculty-admins'
    | '/admin/registration-links'
    | '/dept-admin/approvals'
    | '/dept-admin/assignments'
    | '/dept-admin/dashboard'
    | '/dept-admin/lecturers'
    | '/dept-admin/login'
    | '/faculty/carryovers'
    | '/faculty/courses'
    | '/faculty/dashboard'
    | '/faculty/dept-admins'
    | '/faculty/login'
    | '/faculty/registration-links'
    | '/faculty/result-entry'
    | '/faculty/results'
    | '/faculty/students'
    | '/faculty/transcripts'
    | '/lecturer/dashboard'
    | '/lecturer/entry'
    | '/lecturer/login'
    | '/student/carryovers'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/login'
    | '/student/profile'
    | '/student/register'
    | '/student/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  LoginRoute: typeof LoginRoute
  ProgrammesRoute: typeof ProgrammesRoute
  ResultEntryRoute: typeof ResultEntryRoute
  ResultsRoute: typeof ResultsRoute
  SchoolsRoute: typeof SchoolsRoute
  SessionsRoute: typeof SessionsRoute
  StudentsRoute: typeof StudentsRoute
  TranscriptsRoute: typeof TranscriptsRoute
  ValidationAuditRoute: typeof ValidationAuditRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminFacultyAdminsRoute: typeof AdminFacultyAdminsRoute
  AdminRegistrationLinksRoute: typeof AdminRegistrationLinksRoute
  DeptAdminApprovalsRoute: typeof DeptAdminApprovalsRoute
  DeptAdminAssignmentsRoute: typeof DeptAdminAssignmentsRoute
  DeptAdminDashboardRoute: typeof DeptAdminDashboardRoute
  DeptAdminLecturersRoute: typeof DeptAdminLecturersRoute
  DeptAdminLoginRoute: typeof DeptAdminLoginRoute
  FacultyCarryoversRoute: typeof FacultyCarryoversRoute
  FacultyCoursesRoute: typeof FacultyCoursesRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyDeptAdminsRoute: typeof FacultyDeptAdminsRoute
  FacultyLoginRoute: typeof FacultyLoginRoute
  FacultyRegistrationLinksRoute: typeof FacultyRegistrationLinksRoute
  FacultyResultEntryRoute: typeof FacultyResultEntryRoute
  FacultyResultsRoute: typeof FacultyResultsRoute
  FacultyStudentsRoute: typeof FacultyStudentsRoute
  FacultyTranscriptsRoute: typeof FacultyTranscriptsRoute
  LecturerDashboardRoute: typeof LecturerDashboardRoute
  LecturerEntryRoute: typeof LecturerEntryRoute
  LecturerLoginRoute: typeof LecturerLoginRoute
  StudentCarryoversRoute: typeof StudentCarryoversRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRegisterRoute: typeof StudentRegisterRoute
  StudentResultsRoute: typeof StudentResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-audit': {
      id: '/validation-audit'
      path: '/validation-audit'
      fullPath: '/validation-audit'
      preLoaderRoute: typeof ValidationAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result-entry': {
      id: '/result-entry'
      path: '/result-entry'
      fullPath: '/result-entry'
      preLoaderRoute: typeof ResultEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results': {
      id: '/student/results'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/register': {
      id: '/student/register'
      path: '/student/register'
      fullPath: '/student/register'
      preLoaderRoute: typeof StudentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/carryovers': {
      id: '/student/carryovers'
      path: '/student/carryovers'
      fullPath: '/student/carryovers'
      preLoaderRoute: typeof StudentCarryoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/login': {
      id: '/lecturer/login'
      path: '/lecturer/login'
      fullPath: '/lecturer/login'
      preLoaderRoute: typeof LecturerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/entry': {
      id: '/lecturer/entry'
      path: '/lecturer/entry'
      fullPath: '/lecturer/entry'
      preLoaderRoute: typeof LecturerEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/dashboard': {
      id: '/lecturer/dashboard'
      path: '/lecturer/dashboard'
      fullPath: '/lecturer/dashboard'
      preLoaderRoute: typeof LecturerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/transcripts': {
      id: '/faculty/transcripts'
      path: '/faculty/transcripts'
      fullPath: '/faculty/transcripts'
      preLoaderRoute: typeof FacultyTranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/students': {
      id: '/faculty/students'
      path: '/faculty/students'
      fullPath: '/faculty/students'
      preLoaderRoute: typeof FacultyStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/results': {
      id: '/faculty/results'
      path: '/faculty/results'
      fullPath: '/faculty/results'
      preLoaderRoute: typeof FacultyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/result-entry': {
      id: '/faculty/result-entry'
      path: '/faculty/result-entry'
      fullPath: '/faculty/result-entry'
      preLoaderRoute: typeof FacultyResultEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/registration-links': {
      id: '/faculty/registration-links'
      path: '/faculty/registration-links'
      fullPath: '/faculty/registration-links'
      preLoaderRoute: typeof FacultyRegistrationLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/login': {
      id: '/faculty/login'
      path: '/faculty/login'
      fullPath: '/faculty/login'
      preLoaderRoute: typeof FacultyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dept-admins': {
      id: '/faculty/dept-admins'
      path: '/faculty/dept-admins'
      fullPath: '/faculty/dept-admins'
      preLoaderRoute: typeof FacultyDeptAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/faculty/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/courses': {
      id: '/faculty/courses'
      path: '/faculty/courses'
      fullPath: '/faculty/courses'
      preLoaderRoute: typeof FacultyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/carryovers': {
      id: '/faculty/carryovers'
      path: '/faculty/carryovers'
      fullPath: '/faculty/carryovers'
      preLoaderRoute: typeof FacultyCarryoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/login': {
      id: '/dept-admin/login'
      path: '/dept-admin/login'
      fullPath: '/dept-admin/login'
      preLoaderRoute: typeof DeptAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/lecturers': {
      id: '/dept-admin/lecturers'
      path: '/dept-admin/lecturers'
      fullPath: '/dept-admin/lecturers'
      preLoaderRoute: typeof DeptAdminLecturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/dashboard': {
      id: '/dept-admin/dashboard'
      path: '/dept-admin/dashboard'
      fullPath: '/dept-admin/dashboard'
      preLoaderRoute: typeof DeptAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/assignments': {
      id: '/dept-admin/assignments'
      path: '/dept-admin/assignments'
      fullPath: '/dept-admin/assignments'
      preLoaderRoute: typeof DeptAdminAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin/approvals': {
      id: '/dept-admin/approvals'
      path: '/dept-admin/approvals'
      fullPath: '/dept-admin/approvals'
      preLoaderRoute: typeof DeptAdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registration-links': {
      id: '/admin/registration-links'
      path: '/admin/registration-links'
      fullPath: '/admin/registration-links'
      preLoaderRoute: typeof AdminRegistrationLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculty-admins': {
      id: '/admin/faculty-admins'
      path: '/admin/faculty-admins'
      fullPath: '/admin/faculty-admins'
      preLoaderRoute: typeof AdminFacultyAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/admin/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditLogsRoute: AuditLogsRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  LoginRoute: LoginRoute,
  ProgrammesRoute: ProgrammesRoute,
  ResultEntryRoute: ResultEntryRoute,
  ResultsRoute: ResultsRoute,
  SchoolsRoute: SchoolsRoute,
  SessionsRoute: SessionsRoute,
  StudentsRoute: StudentsRoute,
  TranscriptsRoute: TranscriptsRoute,
  ValidationAuditRoute: ValidationAuditRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminFacultyAdminsRoute: AdminFacultyAdminsRoute,
  AdminRegistrationLinksRoute: AdminRegistrationLinksRoute,
  DeptAdminApprovalsRoute: DeptAdminApprovalsRoute,
  DeptAdminAssignmentsRoute: DeptAdminAssignmentsRoute,
  DeptAdminDashboardRoute: DeptAdminDashboardRoute,
  DeptAdminLecturersRoute: DeptAdminLecturersRoute,
  DeptAdminLoginRoute: DeptAdminLoginRoute,
  FacultyCarryoversRoute: FacultyCarryoversRoute,
  FacultyCoursesRoute: FacultyCoursesRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyDeptAdminsRoute: FacultyDeptAdminsRoute,
  FacultyLoginRoute: FacultyLoginRoute,
  FacultyRegistrationLinksRoute: FacultyRegistrationLinksRoute,
  FacultyResultEntryRoute: FacultyResultEntryRoute,
  FacultyResultsRoute: FacultyResultsRoute,
  FacultyStudentsRoute: FacultyStudentsRoute,
  FacultyTranscriptsRoute: FacultyTranscriptsRoute,
  LecturerDashboardRoute: LecturerDashboardRoute,
  LecturerEntryRoute: LecturerEntryRoute,
  LecturerLoginRoute: LecturerLoginRoute,
  StudentCarryoversRoute: StudentCarryoversRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRegisterRoute: StudentRegisterRoute,
  StudentResultsRoute: StudentResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
