import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CalendarDays, FileText, Megaphone } from "lucide-react";
import { ProtectedStudent } from "@/components/ProtectedStudent";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { useAuthSession } from "@/hooks/use-auth";

export const Route = createFileRoute("/student/services")({
  head: () => ({ meta: [{ title: "Student Services — Kazaure College" }] }),
  component: () => <ProtectedStudent><ServicesPage /></ProtectedStudent>,
});

function ServicesPage() {
  const { session } = useAuthSession();
  const student = useQuery({ queryKey: ["student-services-self", session?.user.id], enabled: !!session, queryFn: async () => { const { data, error } = await supabase.from("students").select("id, faculty_id, department_id, level").eq("user_id", session!.user.id).single(); if (error) throw error; return data; } });
  const fees = useQuery({ queryKey: ["student-fees", student.data?.id], enabled: !!student.data, queryFn: async () => { const { data, error } = await supabase.from("student_fees" as never).select("*").eq("student_id", student.data!.id).order("created_at", { ascending: false }); if (error) throw error; return (data ?? []) as Array<{ id: string; description: string; amount: number; status: string; receipt_number: string | null; paid_at: string | null }>; } });
  const timetable = useQuery({ queryKey: ["student-timetable", student.data?.id], enabled: !!student.data, queryFn: async () => { const { data, error } = await supabase.from("timetables" as never).select("*").eq("faculty_id", student.data!.faculty_id).eq("department_id", student.data!.department_id).eq("level", student.data!.level).order("day").order("start_time"); if (error) throw error; return (data ?? []) as Array<{ id: string; day: string; start_time: string; end_time: string; course_code: string; course_title: string; venue: string | null }>; } });
  const announcements = useQuery({ queryKey: ["student-announcements"], queryFn: async () => { const { data, error } = await supabase.from("announcements" as never).select("id, title, body, published_at").order("published_at", { ascending: false }); if (error) throw error; return (data ?? []) as Array<{ id: string; title: string; body: string; published_at: string | null }>; } });
  return <div className="space-y-6"><div><h2 className="font-serif text-2xl font-bold">Student Services</h2><p className="text-sm text-muted-foreground">Fees, receipts, timetable and college announcements.</p></div><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FileText className="h-4 w-4 text-primary" /> Fees and receipts</CardTitle></CardHeader><CardContent>{fees.data?.length ? <div className="space-y-3">{fees.data.map((fee) => <div key={fee.id} className="flex items-center justify-between gap-3 border-b pb-3 text-sm"><div><p className="font-medium">{fee.description}</p><p className="text-xs text-muted-foreground">{fee.receipt_number ?? "No receipt yet"}</p></div><div className="text-right"><p>₦{Number(fee.amount).toLocaleString()}</p><p className={`text-xs capitalize ${fee.status === "paid" ? "text-primary" : "text-muted-foreground"}`}>{fee.status.replace("_", " ")}</p></div></div>)}</div> : <p className="text-sm text-muted-foreground">No fee records available.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-4 w-4 text-primary" /> Timetable</CardTitle></CardHeader><CardContent>{timetable.data?.length ? <div className="space-y-3">{timetable.data.map((item) => <div key={item.id} className="border-b pb-3 text-sm"><div className="flex justify-between gap-3"><span className="font-medium">{item.course_code} · {item.course_title}</span><span className="text-muted-foreground">{item.day}</span></div><p className="mt-1 text-xs text-muted-foreground">{item.start_time.slice(0, 5)} - {item.end_time.slice(0, 5)}{item.venue ? ` · ${item.venue}` : ""}</p></div>)}</div> : <p className="text-sm text-muted-foreground">No timetable published for your level.</p>}</CardContent></Card></div><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Megaphone className="h-4 w-4 text-primary" /> Announcements</CardTitle></CardHeader><CardContent>{announcements.data?.length ? <div className="space-y-4">{announcements.data.map((item) => <article key={item.id} className="border-b pb-4 last:border-0 last:pb-0"><h3 className="font-serif font-bold text-primary">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.body}</p>{item.published_at && <time className="mt-2 block text-xs text-muted-foreground">{new Date(item.published_at).toLocaleDateString()}</time>}</article>)}</div> : <p className="text-sm text-muted-foreground">No announcements yet.</p>}</CardContent></Card></div>;
}
